CREATE TABLE IF NOT EXISTS story_analysis (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    analysis_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64),
    room_id VARCHAR(64),
    original_story CLOB,
    summary VARCHAR(255),
    target_role VARCHAR(100),
    scene VARCHAR(20),
    emotion VARCHAR(50),
    emotion_level INT,
    complaint_tags VARCHAR(500),
    core_conflict VARCHAR(255),
    visual_character VARCHAR(255),
    vent_tool VARCHAR(255),
    meme_text VARCHAR(100),
    positive_praise VARCHAR(255),
    image_prompt CLOB,
    animation_prompt CLOB,
    safety_level VARCHAR(20),
    confidence DECIMAL(5, 4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
